CREATE TYPE tracking_type AS (
	id bigint,
	joborderitemid bigint,
	joborderid bigint,
	modelid bigint,
	serial character varying,
	jo_no character varying,
	order_type character varying,
	salesorderid bigint,
	so_no character varying,
	po_no character varying,
	customerid bigint,
	customer text,
	"position" character varying,
	positionid bigint,
	position1 character varying,
	position2 character varying,
	modelcode character varying,
	modelname character varying,
	size_w double precision,
	size_d double precision,
	size_h double precision,
	packing_size_w double precision,
	packing_size_d double precision,
	packing_size_h double precision,
	tc_ms date,
	tc_carving date,
	tc_sand date,
	tc_fin date,
	tc_uph date,
	tc_pack date,
	rm_in date,
	rm_out date,
	rm_aging integer,
	rm_lt integer,
	mc_in date,
	mc_out date,
	mc_aging integer,
	mc_lt integer,
	cv_in date,
	cv_out date,
	cv_carver integer,
	cv_aging integer,
	cv_lt integer,
	sn_in date,
	sn_out date,
	sn_aging integer,
	sn_lt integer,
	fn_in date,
	fn_out date,
	fn_aging integer,
	fn_lt integer,
	up_in date,
	up_out date,
	up_aging integer,
	up_lt integer,
	pack_in date,
	pack_out date,
	pack_aging integer,
	pack_lt integer,
	ship_date date,
	ship_to date,
	ship_aging integer,
	ship_lt integer,
	remark text
);
